/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacymanagementsystem;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author shakyaninja
 */
public class AddSalesInfo extends javax.swing.JFrame {
    PreparedStatement pst = null;
    /**
     * Creates new form AddSalesInfo
     */
    public AddSalesInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        medName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        totalPrice = new javax.swing.JTextField();
        addSales = new javax.swing.JButton();
        Done = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        patientName = new javax.swing.JTextField();
        Quantity = new javax.swing.JSpinner();
        Rate = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(null);
        getContentPane().add(medName);
        medName.setBounds(350, 200, 220, 30);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Medicine Name:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 200, 200, 29);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add Sales Info");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-20, 40, 800, 57);

        totalPrice.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                totalPricePropertyChange(evt);
            }
        });
        getContentPane().add(totalPrice);
        totalPrice.setBounds(350, 400, 140, 30);

        addSales.setBackground(new java.awt.Color(102, 204, 0));
        addSales.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        addSales.setForeground(new java.awt.Color(255, 255, 255));
        addSales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacymanagementsystem/blue_sale.png"))); // NOI18N
        addSales.setBorder(null);
        addSales.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSalesActionPerformed(evt);
            }
        });
        getContentPane().add(addSales);
        addSales.setBounds(240, 520, 330, 50);

        Done.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Done.setText("Done");
        Done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneActionPerformed(evt);
            }
        });
        getContentPane().add(Done);
        Done.setBounds(30, 520, 120, 50);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Patient name:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 250, 180, 29);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total Price:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(180, 400, 140, 29);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("View All");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(640, 520, 130, 50);
        getContentPane().add(patientName);
        patientName.setBounds(350, 250, 220, 30);
        getContentPane().add(Quantity);
        Quantity.setBounds(350, 350, 39, 28);
        getContentPane().add(Rate);
        Rate.setBounds(350, 300, 220, 28);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Rate:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(250, 300, 70, 29);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Quantity:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(200, 350, 120, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacymanagementsystem/addsalesbg.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ViewAllSales v = new ViewAllSales();
        v.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSalesActionPerformed
        // TODO add your handling code here:
        //adds student to database
        String MedName, PatientName;
        int rate;
        int quantity;
        MedName = this.medName.getText();
        PatientName = this.patientName.getText();
        rate = (Integer) Rate.getValue();
        quantity = (Integer) Quantity.getValue();
        
        try {
            DBConnect.connectdb();
            String sql = "INSERT INTO `Sales_info`( `medicine_name`, `patient_name`, `rate`, `quantity`) VALUES ('" + MedName + "','" + PatientName + "','" + rate + "','" + quantity + "') ";
            pst = DBConnect.conn.prepareStatement(sql);
            int a = pst.executeUpdate();
            if (a != 0) {
                JOptionPane.showMessageDialog(null, "Sales Added Successfully !");
                AddSalesInfo b = new AddSalesInfo();
                b.setVisible(true);
                this.dispose();
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_addSalesActionPerformed

    private void DoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneActionPerformed
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_DoneActionPerformed

    private void totalPricePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_totalPricePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_totalPricePropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSalesInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSalesInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSalesInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSalesInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSalesInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Done;
    private javax.swing.JSpinner Quantity;
    private javax.swing.JSpinner Rate;
    private javax.swing.JButton addSales;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField medName;
    private javax.swing.JTextField patientName;
    private javax.swing.JTextField totalPrice;
    // End of variables declaration//GEN-END:variables
}
