/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacymanagementsystem;

/**
 *
 * @author Luja Shakya
 */
public class FrontUI extends javax.swing.JFrame {

    /**
     * Creates new form FrontUI
     */
    public FrontUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        frontUITitle = new javax.swing.JLabel();
        addMedicine = new javax.swing.JButton();
        updateMedicine = new javax.swing.JButton();
        removesMedicine = new javax.swing.JButton();
        addSales = new javax.swing.JButton();
        checkExpiry = new javax.swing.JButton();
        makeStatement = new javax.swing.JButton();
        addImports = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.lightGray);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacymanagementsystem/close_red.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setPreferredSize(new java.awt.Dimension(5, 5));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(770, 0, 30, 30);

        frontUITitle.setFont(new java.awt.Font("Segoe UI Semibold", 1, 44)); // NOI18N
        frontUITitle.setForeground(new java.awt.Color(0, 153, 204));
        frontUITitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        frontUITitle.setText("Pharmacy Management System");
        jPanel1.add(frontUITitle);
        frontUITitle.setBounds(0, 30, 800, 64);

        addMedicine.setBackground(new java.awt.Color(102, 204, 0));
        addMedicine.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        addMedicine.setForeground(new java.awt.Color(255, 255, 255));
        addMedicine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacymanagementsystem/buttons_green.png"))); // NOI18N
        addMedicine.setBorder(null);
        addMedicine.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMedicineActionPerformed(evt);
            }
        });
        jPanel1.add(addMedicine);
        addMedicine.setBounds(240, 140, 330, 50);

        updateMedicine.setBackground(new java.awt.Color(0, 153, 255));
        updateMedicine.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        updateMedicine.setForeground(new java.awt.Color(255, 255, 255));
        updateMedicine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacymanagementsystem/blue_up.png"))); // NOI18N
        updateMedicine.setBorder(null);
        updateMedicine.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateMedicine.setMultiClickThreshhold(6L);
        updateMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMedicineActionPerformed(evt);
            }
        });
        jPanel1.add(updateMedicine);
        updateMedicine.setBounds(60, 220, 310, 60);

        removesMedicine.setBackground(new java.awt.Color(254, 52, 55));
        removesMedicine.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        removesMedicine.setForeground(new java.awt.Color(255, 255, 255));
        removesMedicine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacymanagementsystem/buttons_red.png"))); // NOI18N
        removesMedicine.setBorder(null);
        removesMedicine.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removesMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removesMedicineActionPerformed(evt);
            }
        });
        jPanel1.add(removesMedicine);
        removesMedicine.setBounds(430, 220, 320, 57);

        addSales.setBackground(new java.awt.Color(0, 153, 255));
        addSales.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        addSales.setForeground(new java.awt.Color(255, 255, 255));
        addSales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacymanagementsystem/blue_sale.png"))); // NOI18N
        addSales.setBorder(null);
        addSales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSalesActionPerformed(evt);
            }
        });
        jPanel1.add(addSales);
        addSales.setBounds(430, 310, 320, 57);

        checkExpiry.setBackground(new java.awt.Color(0, 153, 255));
        checkExpiry.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        checkExpiry.setForeground(new java.awt.Color(255, 255, 255));
        checkExpiry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacymanagementsystem/blue_check.png"))); // NOI18N
        checkExpiry.setBorder(null);
        checkExpiry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkExpiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkExpiryActionPerformed(evt);
            }
        });
        jPanel1.add(checkExpiry);
        checkExpiry.setBounds(60, 310, 310, 57);

        makeStatement.setBackground(new java.awt.Color(0, 153, 255));
        makeStatement.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        makeStatement.setForeground(new java.awt.Color(255, 255, 255));
        makeStatement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacymanagementsystem/blue_make.png"))); // NOI18N
        makeStatement.setBorder(null);
        makeStatement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(makeStatement);
        makeStatement.setBounds(60, 400, 310, 57);

        addImports.setBackground(new java.awt.Color(0, 153, 255));
        addImports.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        addImports.setForeground(new java.awt.Color(255, 255, 255));
        addImports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacymanagementsystem/blue_import.png"))); // NOI18N
        addImports.setBorder(null);
        addImports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addImports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addImportsActionPerformed(evt);
            }
        });
        jPanel1.add(addImports);
        addImports.setBounds(430, 400, 320, 57);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacymanagementsystem/Background.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMedicineActionPerformed
        // TODO add your handling code here:
        AddMedicineInfo a = new AddMedicineInfo();
        a.setVisible(true);
    }//GEN-LAST:event_addMedicineActionPerformed

    private void updateMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMedicineActionPerformed
        // TODO add your handling code here:
        UpdateMedicineInfo u = new UpdateMedicineInfo();
        u.setVisible(true);
    }//GEN-LAST:event_updateMedicineActionPerformed

    private void removesMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removesMedicineActionPerformed
        // TODO add your handling code here:
        RemoveMedicineInfo r = new RemoveMedicineInfo();
        r.setVisible(true);
    }//GEN-LAST:event_removesMedicineActionPerformed

    private void addSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSalesActionPerformed
        // TODO add your handling code here:
        AddSalesInfo s = new AddSalesInfo();
        s.setVisible(true);
    }//GEN-LAST:event_addSalesActionPerformed

    private void addImportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addImportsActionPerformed
        // TODO add your handling code here:
        AddImports i = new AddImports();
        i.setVisible(true);
    }//GEN-LAST:event_addImportsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void checkExpiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkExpiryActionPerformed
        // TODO add your handling code here:
        CheckExpiryDates c=new CheckExpiryDates();
        c.setVisible(true);
    }//GEN-LAST:event_checkExpiryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrontUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrontUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrontUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrontUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrontUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addImports;
    private javax.swing.JButton addMedicine;
    private javax.swing.JButton addSales;
    private javax.swing.JButton checkExpiry;
    private javax.swing.JLabel frontUITitle;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton makeStatement;
    private javax.swing.JButton removesMedicine;
    private javax.swing.JButton updateMedicine;
    // End of variables declaration//GEN-END:variables
}
